sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: '46.0'
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
  - secure: qDEr4+mFT+m2Bi5dZAHk85SmoKmOlYe5ymZxZbAF3AFkkro9HIvJfkk/DITdrBJvcAFYpR3Z4THNz0G9+cRd++43YAcb8cA8v23KX6AobVHbBeuwkT4/AQtefhO4LG3mF6zwUIgKfsKmRYjJRma4Rb2NBi0YUIRks6rZaDUhu5soHt8vmjMxwyO7LwZPK0Uso2BqUwrr2G0dKnDBjEBxEyllNi/CaFjbrG1wZRDzyZfIhbSfX4stnAeILs9lp6W4O5qUrndikR6M3zd+vhYGGhUIB6HCNEk/tlOBYHWvKxJoNfFaqHIiNWMHuJSOZl43a9xRUohKwHxO5lwHApzbMoFVppEKck5bgbUEsfhA7BQylKN3Eg0+OE7FHaMEBMNdtQgyHbgw0Ovqe9B1k6cx557FYd+ABJR91pQPbi/XDpeRpTwKAY0OL0ikAy89Hv2HpesAQ6OkxOO044yLhKa0w0DzPoPfIvJGGx12O1AqK+hKSEtxsGMBwvvRhBBMusYCMHKQOt5u4uRoRuO9ieqEyGE7BEIqdRVQ0r9+OlulMxxo2AwiyYMhLSH6XF34EUm/ONyaf72PS2UrWBg3We+3x4/8s6AoXrT/Xa3JKr94wYBGu2bw2/EvZ6SVRgt3qZNmx1Anor+rFdGUouJ33n74tE9ow/dQSUKsqaRunSnBVC4=
  - secure: M8P7gAQKpX+kF0KdTcdQgVie4DxN8frrxhYIwCk8UWyZweDXFCJmBeMFfwXzGSLKR+HBSqQgGP7PJxhYPSQe/A9jzR3x7Ipc8AlxTKVrG0Rjee+7z3hiEtX3ERmLW98Ia2R/ahQFtDwfiksKwCRFU3P92cGvNQmuY3gcpCHHIHtYWRBik6XCrxSm72WCRgAfWaXcqkitJDJGhMZnr+4DrGtkv+Nm6AdkJ8LF5eDXXwbXAn+bhq4DgZbu1ThVNWBkELGfj+zSOniYMzN/hicKSzXQUA2QLbv4irz7CgcY4FZkYkTtV3sI6zoNtJ+bY9pAZGQqp+JdrxYNNnNFpWR7t1Ri3N90MY9EQhbWC9XXECC/PskYP8zzkv8NetKOGBZnN7U67pV+xu7RM+yb41mTaRucV0U9qNUEXTo9d2TJ95h5seMTWo1tC1Bp6Nz/LwHe3IKiw1gpdlA5GpCll74bNmjawzqHSnax/ggMVmy0rjgDdzrWISveY33B6MToEvzqhH1oeGLG2QyZm5qm+39zEluTRy6WczS9HlhsfaTlwA8tdnrd0vyljtNIDkrarG6u7ZOW7fOcTAt7+RRvvmq87uMj+47mcp9qGiLY3hrXV/yOlzAe5bFwe6JYJQTarlipQ0yzrXoknvhKC+KgwM43MpjqM+f4iugGHfWrUdz2yWQ=
  - secure: GRmA5qVsjWpzW/+dkEHmWCMhe9eCMseFgcgl6J0Y8tfswjSgp6caWK9sX5WgXQBVyU+6Kms5agj/vqr+a6GKZ07ORcLme9s6e8zPr82rs+16I+Hyr/0VJ+aeEm+ScWhNAFyXasOZll+/XgUoGFwi/uSugAANj6hlYE+mhc/3nDDy+GeIVZj8PDljoy+S8IzoJhK/44ka9ERkMlflFxwpS27YrYE6YrMKS/EiOnF+QHJul64mLt2YpScGnmaOYKlO+ahshSkQYiDz+DssvPwksIOjQXw4w43/lLxtRNlBy9nX9cjBi+/xF0gD7fDVYZ+TIJVpmeZCS25eWQv5T85b7rARsg5r//Podnx6eM2zwkB4Aj63tgRD0L3mzWq9ig4AQ8DVHWzh3gM3cjObkDHVdy/JwysBEjYHZtAONZkmxrSSZpuCBpW2GKn3zwXv5lIS90uFKVqssSV5gGAqi3xQYGWwjdxbSamG4qfqVSGjshXLLoGnSJH9UgwMBuBG7rA7nP7IPAJhDFd21qMy3TA7Sa9Cg6dMJEN5yLSGtEn8tKJI2Xf0NwshocRQ6KBQ/HxZVMZ6wIXKe5e2AP43VAgZsM5Q6qyu+L8TLwcIUNEpG2/lO8McD3dz/mbRuMmly7xwE4DY5O0A9dwrMJxlELJ7YYJgPS4gyawEdIagAgcHJ28=
before_install:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$password"
  -in id_rsa.enc -out deploy_key -d; fi
after_success:
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"

